// <auto-generated />
namespace MrpService.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open MrpService.Data

[<DbContext(typeof<MRPContext>)>]
[<Migration("20250409062434_InitialCreate")>]
type InitialCreate() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Products"
            ,columns = (fun table -> 
            {|
                ProductId =
                    table.Column<Int64>(
                        nullable = false
                        ,``type`` = "bigint"
                    ).Annotation("SqlServer:Identity", "1, 1")
                ProductName =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(100)"
                        ,maxLength = Nullable(100)
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Products", (fun x -> (x.ProductId) :> obj)
                    ) |> ignore
                )
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "Stages"
            ,columns = (fun table -> 
            {|
                StageId =
                    table.Column<Int64>(
                        nullable = false
                        ,``type`` = "bigint"
                    ).Annotation("SqlServer:Identity", "1, 1")
                StageDescr =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(50)"
                        ,maxLength = Nullable(50)
                    )
                StageCode =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(50)"
                        ,maxLength = Nullable(50)
                    )
                ParentStageId =
                    table.Column<Int64>(
                        nullable = true
                        ,``type`` = "bigint"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Stages", (fun x -> (x.StageId) :> obj)
                    ) |> ignore
                    table.ForeignKey(
                        name = "FK_Stages_Stages_ParentStageId"
                        ,column = (fun x -> (x.ParentStageId) :> obj)
                        ,principalTable = "Stages"
                        ,principalColumn = "StageId"
                        ,onDelete = ReferentialAction.Restrict
                        ) |> ignore

                )
        ) |> ignore

        migrationBuilder.CreateTable(
            name = "Positions"
            ,columns = (fun table -> 
            {|
                PosId =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "int"
                    ).Annotation("SqlServer:Identity", "1, 1")
                PositionCode =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(10)"
                        ,maxLength = Nullable(10)
                    )
                PositionDescr =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "nvarchar(50)"
                        ,maxLength = Nullable(50)
                    )
                StageId =
                    table.Column<Int64>(
                        nullable = false
                        ,``type`` = "bigint"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Positions", (fun x -> (x.PosId) :> obj)
                    ) |> ignore
                    table.ForeignKey(
                        name = "FK_Positions_Stages_StageId"
                        ,column = (fun x -> (x.StageId) :> obj)
                        ,principalTable = "Stages"
                        ,principalColumn = "StageId"
                        ,onDelete = ReferentialAction.Cascade
                        ) |> ignore

                )
        ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_Positions_StageId"
            ,table = "Positions"
            ,column = "StageId"
            ) |> ignore

        migrationBuilder.CreateIndex(
            name = "IX_Stages_ParentStageId"
            ,table = "Stages"
            ,column = "ParentStageId"
            ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Positions"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "Products"
            ) |> ignore

        migrationBuilder.DropTable(
            name = "Stages"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 128) |> ignore

        modelBuilder.Entity("MrpService.Models.Position", (fun b ->

            b.Property<int>("PosId")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("int")
                |> ignore

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosId"), 1L, 1) |> ignore

            b.Property<string>("PositionCode")
                .IsRequired(true)
                .HasMaxLength(10)
                .HasColumnType("nvarchar(10)")
                |> ignore

            b.Property<string>("PositionDescr")
                .IsRequired(true)
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)")
                |> ignore

            b.Property<Int64>("StageId")
                .IsRequired(true)
                .HasColumnType("bigint")
                |> ignore

            b.HasKey("PosId")
                |> ignore


            b.HasIndex("StageId")
                |> ignore

            b.ToTable("Positions") |> ignore

        )) |> ignore

        modelBuilder.Entity("MrpService.Models.Product", (fun b ->

            b.Property<Int64>("ProductId")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                |> ignore

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<Int64>("ProductId"), 1L, 1) |> ignore

            b.Property<string>("ProductName")
                .IsRequired(true)
                .HasMaxLength(100)
                .HasColumnType("nvarchar(100)")
                |> ignore

            b.HasKey("ProductId")
                |> ignore


            b.ToTable("Products") |> ignore

        )) |> ignore

        modelBuilder.Entity("MrpService.Models.Stage", (fun b ->

            b.Property<Int64>("StageId")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint")
                |> ignore

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<Int64>("StageId"), 1L, 1) |> ignore

            b.Property<Nullable<Int64>>("ParentStageId")
                .IsRequired(false)
                .HasColumnType("bigint")
                |> ignore

            b.Property<string>("StageCode")
                .IsRequired(true)
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)")
                |> ignore

            b.Property<string>("StageDescr")
                .IsRequired(true)
                .HasMaxLength(50)
                .HasColumnType("nvarchar(50)")
                |> ignore

            b.HasKey("StageId")
                |> ignore


            b.HasIndex("ParentStageId")
                |> ignore

            b.ToTable("Stages") |> ignore

        )) |> ignore
        modelBuilder.Entity("MrpService.Models.Position", (fun b ->
            b.HasOne("MrpService.Models.Stage", null)
                .WithMany("Positions")
                .HasForeignKey("StageId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired()
                |> ignore

        )) |> ignore
        modelBuilder.Entity("MrpService.Models.Stage", (fun b ->
            b.HasOne("MrpService.Models.Stage", null)
                .WithMany("ChildStages")
                .HasForeignKey("ParentStageId")
                .OnDelete(DeleteBehavior.Restrict)
                |> ignore

        )) |> ignore
        modelBuilder.Entity("MrpService.Models.Stage", (fun b ->

            b.Navigation("ChildStages")
            |> ignore

            b.Navigation("Positions")
            |> ignore
        )) |> ignore

